name: swansport_core
description: Core shared utilities for SwanSport.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
