"""Generate privacy allowlists from checked-in code, never runtime user values.

Run after adding routes/RPCs/source files; --check detects stale Dart/SQL lists.
"""
from pathlib import Path
import re
import sys

root = Path(__file__).resolve().parent.parent
routes = {'/', '/unknown', '/hata-merkezi'}
for relative in ['apps/swansport_app/lib/app/swansport_app.dart',
                 'apps/swansport_console/lib/app/modules/module_registry.dart']:
    routes.update(re.findall(r"'(/[a-zA-Z0-9_/-]*)'", (root / relative).read_text(encoding='utf-8')))
operations = {'unknown', 'navigation', 'auth', 'storage', 'framework', 'async', 'provider',
              'action:facility_reservation', 'action:finance_adjustment', 'action:support_ticket',
              'action:push_open', 'action:consistency'}
for file in (root / 'supabase/migrations').glob('*.sql'):
    if file.name.startswith('0086_'):
        continue  # Diagnostics must never instrument its own transport.
    text = file.read_text(encoding='utf-8')
    operations.update('rpc:' + name for name in re.findall(
        r'create\s+(?:or\s+replace\s+)?function\s+public\.([a-z_][a-z_0-9]*)', text, re.I))
    operations.update('table:' + name for name in re.findall(
        r'create\s+table\s+(?:if\s+not\s+exists\s+)?public\.([a-z_][a-z_0-9]*)', text, re.I))
sources = set()
for folder, package in [('apps/swansport_app', 'swansport_app'),
                        ('apps/swansport_console', 'swansport_console'),
                        ('packages/swansport_data', 'swansport_data'),
                        ('packages/swansport_core', 'swansport_core')]:
    for file in (root / folder / 'lib').rglob('*.dart'):
        sources.add('package:' + package + '/' + file.relative_to(root / folder / 'lib').as_posix())

dart = '// Generated by tools/generate_diagnostics_catalog.py; code identifiers only.\n'
for name, entries in [('diagnosticRoutes', routes), ('diagnosticOperations', operations), ('diagnosticSources', sources)]:
    dart += f'const {name} = <String>{{\n' + ''.join(f"  '{entry}',\n" for entry in sorted(entries)) + '};\n'
target = root / 'packages/swansport_data/lib/src/diagnostics_catalog.dart'
sql = 'insert into public.diagnostic_catalog(category, value) values\n'
sql += ',\n'.join(f"('{category}', '{entry}')" for category, values in
                 [('route', routes), ('operation', operations), ('source', sources)] for entry in sorted(values))
sql += '\non conflict do nothing;'
migration = root / 'supabase/migrations/0086_diagnostics_center.sql'
if '-- CATALOG START' in migration.read_text(encoding='utf-8'):
    original = migration.read_text(encoding='utf-8')
    updated = re.sub(r'-- CATALOG START.*?-- CATALOG END', '-- CATALOG START\n' + sql + '\n-- CATALOG END', original, flags=re.S)
else:
    raise SystemExit('Migration catalog markers missing')
if '--check' in sys.argv:
    if not target.exists() or target.read_text(encoding='utf-8') != dart or original != updated:
        raise SystemExit('Diagnostic allowlists stale: run python tools/generate_diagnostics_catalog.py')
else:
    target.write_text(dart, encoding='utf-8')
    migration.write_text(updated, encoding='utf-8')
print(f'Diagnostics catalog: {len(routes)} routes, {len(operations)} operations, {len(sources)} sources')
