name: swansport_design_system
description: Material 3 based SwanSport design system package.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
